---
- name: Install and run Redis on VM
  hosts: all
  become: true

  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Install Redis
      apt:
        name: redis-server
        state: present

    - name: Enable and start Redis server
      systemd:
        name: redis-server
        enabled: yes
        state: started

    - name: Ensure Redis is listening on all interfaces
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind'
        line: 'bind 0.0.0.0'
        backup: yes

    - name: Restart Redis to apply configuration changes
      systemd:
        name: redis-server
        state: restarted
